version: '3.7'

services:

  my-todo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - '.:/app'
      - '/app/node_modules'
    # ports:
    #   - 3001:3000
    labels:
      # Traefik dan foydalanishga ruhsat ushbu servis uchun
      - traefik.enable=true
      # Docker service ichda ishlash uchun HTTPS port
      - traefik.http.services.app.loadbalancer.server.port=3001
      # Traefik foydalanadigan domen
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`traefik.zafardevops.uz`)
      # Foydalaniladigan networkni kiritish
      - traefik.docker.network=traefik-public
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
