version: '3.7'

services:

  mytodo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
